[Deed]
crs = "32647"
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "s13", 711701.027, 810081.178],
  [2, "B", "s30", 711581.476, 810204.956],
  [3, "C", "$17", 711619.233, 810248.648],
  [4, "D", "s100", 711762.764, 810133.464],
  [5, "E", "s13", 711701.027, 810.081],
]