[Deed]
crs = "32647"
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "s41", 711042.723, 810293.807],
  [2, "B", "520", 711275.096, 810520.089],
  [3, "C", "s21", 711325.209, 810466.417],
  [4, "D", "19", 711354.507, 810440.839],
  [5, "E", "s24", 711494.218, 810313.001],
  [6, "F", "$23", 711488.109, 810300.804],
  [7, "G", "s22", 711328.714, 810147.726],
  [8, "H", "s42", 711420.856, 810053.505],
  [9, "I", "S43", 711349.998, 809983.554],
  [10, "J", "541", 711042.723, 810293.807],
]