[META]
DOL_Office = "Narathivas"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = true
marker = [
  [1, "A", "s43", 711349.998, 809983.554],
  [2, "B", "542", 711420.856, 810053.505],
  [3, "C", "s22", 711328.714, 810147.726],
  [4, "D", "s23", 711488.109, 810300.804],
  [5, "E", "530", 711581.476, 810204.956],
  [6, "F", "329", 711526.602, 810148.263],
  [7, "G", "s28", 711469.291, 810096.547],
  [8, "H", "s27", 711473.159, 810092.493],
  [9, "I", "s26", 711441.737, 810060.689],
  [10, "J", "25", 711452.043, 810050.263],
  [11, "K", "s4", 711366.012, 809967.301],
]