[Deed]
crs = "32647"
unit = "meter"
polygon_closed = true
marker = [
  [1, "A", "s81.", 711456.200, 809873.918],
  [2, "B", "s4", 711366.012, 809967.301],
  [3, "C", "S25", 711452.043, 810050.263],
  [4, "D", "526", 711441.737, 810060.689],
  [5, "E", "527", 711473.159, 810092.493],
  [6, "F", "528", 711469.291, 810096.547],
  [7, "G", "s29", 711526.602, 810148.263],
  [8, "H", "531", 711624.835, 810051.076],
  [9, "I", "532", 711562.689, 809987.191],
  [10, "J", "533", 711574.042, 809972.324],
]