[META]
DOL_Office = "Narathivas"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "533", 711574.042, 809972.324],
  [2, "B", "532", 711562.689, 809987.191],
  [3, "C", "531", 711624.835, 810051.076],
  [4, "D", "58.0.", 711644.466, 810031.568],
  [5, "E", "s33", 711574.042, 809972.324],
]