[META]
DOL_Office = "Narathivas"

[Deed]
Survey_Type = "MAP-L1"
EPSG = 24047
unit = "meter"
polygon_closed = false
marker = [
  [1, "A", "s24", 711494.218, 810313.001],
  [2, "B", "S18", 711510.841, 810323.391],
  [3, "C", "520", 711275.096, 810520.089],
  [4, "D", "s21", 711325.209, 810466.417],
  [5, "E", "s19", 711354.507, 810440.839],
  [6, "F", "$24", 711494.218, 810313.001],
]